import type { RoutineCard, RoutineLink } from "./types";

export const routineCards: RoutineCard[] = [
  {
    id: "nasa",
    tool: "SAS",
    icon: "table",
    name: "NASA",
    owner: "Fatima Lavouras",
    ownerPresence: "online",
    status: "Concluído",
    detail: "insumo inicial disponivel",
    completedAt: "06:32",
    color: "green",
  },
  {
    id: "gsin",
    tool: "SAS",
    icon: "table",
    name: "GSIN",
    owner: "Fatima Lavouras",
    ownerPresence: "ausente",
    status: "Em atraso",
    detail: "retorno de sinistros acima do previsto",
    forecast: "07:14",
    variance: "+11m",
    varianceTone: "negative",
    color: "amber",
  },
  {
    id: "crivo",
    tool: "SAS",
    icon: "table",
    name: "Crivo",
    owner: "Fatima Lavouras",
    ownerPresence: "online",
    status: "Concluído",
    detail: "regras de elegibilidade prontas",
    completedAt: "06:28",
    color: "green",
  },
  {
    id: "cotacao-variaveis",
    tool: "SAS",
    icon: "table",
    name: "Cotacao Variaveis",
    owner: "Fatima Lavouras",
    ownerPresence: "online",
    status: "Concluído",
    detail: "parametros liberados",
    completedAt: "06:31",
    color: "green",
  },
  {
    id: "dwat",
    tool: "ORCL",
    icon: "table",
    name: "DWAT",
    owner: "Sistema automatico",
    ownerPresence: "online",
    status: "Concluído",
    detail: "carga automatica concluida",
    completedAt: "06:20",
    color: "green",
  },
  {
    id: "dwre",
    tool: "ORCL",
    icon: "table",
    name: "DWRE",
    owner: "Sistema automatico",
    ownerPresence: "online",
    status: "Concluído",
    detail: "carga automatica concluida",
    completedAt: "06:22",
    color: "green",
  },
  {
    id: "edw",
    tool: "ORCL",
    icon: "table",
    name: "EDW",
    owner: "Sistema automatico",
    ownerPresence: "online",
    status: "Concluído",
    detail: "carga automatica concluida",
    completedAt: "06:24",
    color: "green",
  },
  {
    id: "cbo",
    tool: "SAS",
    icon: "table",
    name: "CBO",
    owner: "Fatima Lavouras",
    ownerPresence: "online",
    status: "Concluído",
    detail: "base preparada",
    completedAt: "06:35",
    color: "green",
  },
  {
    id: "ft-auto-emissao",
    tool: "SQL",
    icon: "table",
    name: "FT_AUTO_EMISSAO",
    owner: "Isaque Pimentel",
    ownerPresence: "online",
    status: "Concluído",
    detail: "lote principal liberado",
    completedAt: "07:08",
    color: "green",
  },
  {
    id: "ft-auto-recompensa",
    tool: "SQL",
    icon: "table",
    name: "FT_AUTO_RECOMPENSA",
    owner: "Rafael Rocha",
    ownerPresence: "online",
    status: "Concluído",
    detail: "dependencia: DWAT",
    completedAt: "06:54",
    color: "green",
  },
  {
    id: "ft-auto-propostas-diarias",
    tool: "SQL",
    icon: "table",
    name: "FT_AUTO_PROPOSTAS_DIARIAS",
    owner: "Tuany",
    ownerPresence: "online",
    status: "Executando",
    detail: "janela aberta apos emissao",
    forecast: "07:35",
    variance: "+6m",
    varianceTone: "negative",
    color: "blue",
  },
  {
    id: "ft-auto-propostas-mensais",
    tool: "SQL",
    icon: "table",
    name: "FT_AUTO_PROPOSTAS_MENSAIS",
    owner: "Tuany",
    ownerPresence: "online",
    status: "Executando",
    detail: "processando consolidacao mensal",
    forecast: "07:42",
    variance: "+3m",
    varianceTone: "negative",
    color: "blue",
  },
  {
    id: "ft-auto-propostas-pendentes",
    tool: "SQL",
    icon: "table",
    name: "FT_AUTO_PROPOSTAS_PENDENTES",
    owner: "Rafael Rocha",
    ownerPresence: "online",
    status: "Aguardando",
    detail: "dep.: diarias e mensais",
    forecast: "08:05",
    color: "gray",
  },
  {
    id: "ft-auto-a-renovar",
    tool: "SQL",
    icon: "table",
    name: "FT_AUTO_A_RENOVAR",
    owner: "Tuany",
    ownerPresence: "online",
    status: "Executando",
    detail: "renovacoes em lote",
    forecast: "07:48",
    variance: "-2m",
    varianceTone: "positive",
    color: "blue",
  },
  {
    id: "ft-auto-renovados",
    tool: "SQL",
    icon: "table",
    name: "FT_AUTO_RENOVADOS",
    owner: "Tuany",
    ownerPresence: "offline",
    status: "Aguardando",
    detail: "dep.: emissao e pendentes",
    forecast: "08:18",
    color: "gray",
  },
  {
    id: "ft-auto-sinistros-avisados",
    tool: "SQL",
    icon: "table",
    name: "FT_AUTO_SINISTROS_AVISADOS",
    owner: "Rafael Rocha",
    ownerPresence: "online",
    status: "Em atraso",
    detail: "GSIN ainda nao liberou a janela",
    forecast: "07:28",
    variance: "+11m",
    varianceTone: "negative",
    color: "amber",
  },
  {
    id: "ft-auto-sinistros-pagos",
    tool: "SQL",
    icon: "table",
    name: "FT_AUTO_SINISTROS_PAGOS",
    owner: "Rafael Rocha",
    ownerPresence: "online",
    status: "Aguardando",
    detail: "dependencia: GSIN",
    forecast: "07:36",
    variance: "+11m",
    varianceTone: "negative",
    color: "gray",
  },
  {
    id: "ft-auto-cotacao",
    tool: "SQL",
    icon: "table",
    name: "FT_AUTO_COTACAO",
    owner: "Tuany",
    ownerPresence: "online",
    status: "Executando",
    detail: "cotacao individual em processamento",
    forecast: "07:52",
    variance: "+2m",
    varianceTone: "negative",
    color: "blue",
  },
  {
    id: "ft-auto-cotacao-d30",
    tool: "SQL",
    icon: "table",
    name: "FT_AUTO_COTACAO_D30",
    owner: "Tuany",
    ownerPresence: "online",
    status: "Executando",
    detail: "janela D30 em paralelo",
    forecast: "07:58",
    variance: "+1m",
    varianceTone: "negative",
    color: "blue",
  },
  {
    id: "ft-auto-cbo",
    tool: "SQL",
    icon: "table",
    name: "FT_AUTO_CBO",
    owner: "Fatima Lavouras",
    ownerPresence: "online",
    status: "Concluído",
    detail: "carga CBO sincronizada",
    completedAt: "07:16",
    color: "green",
  },
  {
    id: "ft-prod-agreg-autore-diario",
    tool: "SQL",
    icon: "table",
    name: "FT_PROD_AGREG_AUTORE_DIARIO",
    owner: "Rafael Rocha",
    ownerPresence: "online",
    status: "Concluído",
    detail: "dep.: DWAT, DWRE e EDW",
    completedAt: "06:58",
    color: "green",
  },
  {
    id: "cubo-emissao-auto",
    tool: "MSTR",
    icon: "cube",
    name: "Cubo Emissao Auto",
    owner: "Isaque Pimentel",
    ownerPresence: "online",
    status: "Executando",
    detail: "publicacao da emissao em andamento",
    forecast: "08:10",
    variance: "+4m",
    varianceTone: "negative",
    color: "blue",
  },
  {
    id: "cubo-recompensa",
    tool: "MSTR",
    icon: "cube",
    name: "Cubo Recompensa",
    owner: "Isaque Pimentel",
    ownerPresence: "online",
    status: "Executando",
    detail: "refresh iniciado pelo lote de recompensa",
    forecast: "07:20",
    variance: "-4m",
    varianceTone: "positive",
    color: "blue",
  },
  {
    id: "cubo-propostas-pendentes",
    tool: "MSTR",
    icon: "cube",
    name: "Cubo Propostas Pendentes",
    owner: "Isaque Pimentel",
    ownerPresence: "online",
    status: "Aguardando",
    detail: "dep.: diarias e mensais",
    forecast: "08:18",
    color: "gray",
  },
  {
    id: "cubo-cotacao-auto-individual",
    tool: "MSTR",
    icon: "cube",
    name: "Cubo Cotacao Auto Individual",
    owner: "Isaque Pimentel",
    ownerPresence: "online",
    status: "Aguardando",
    detail: "dep.: cotacao e D30",
    forecast: "08:22",
    color: "gray",
  },
  {
    id: "cubo-sinistros-avisados",
    tool: "MSTR",
    icon: "cube",
    name: "Cubo Sinistros Avisados",
    owner: "Isaque Pimentel",
    ownerPresence: "online",
    status: "Aguardando",
    detail: "aguardando liberacao do GSIN",
    forecast: "07:45",
    variance: "+11m",
    varianceTone: "negative",
    color: "gray",
  },
  {
    id: "cubo-sinistros-pagos",
    tool: "MSTR",
    icon: "cube",
    name: "Cubo Sinistros Pagos",
    owner: "Isaque Pimentel",
    ownerPresence: "online",
    status: "Aguardando",
    detail: "dep.: sinistros pagos",
    forecast: "07:52",
    variance: "+11m",
    varianceTone: "negative",
    color: "gray",
  },
  {
    id: "cubo-producao-auto-re",
    tool: "MSTR",
    icon: "cube",
    name: "Cubo Producao Auto/RE",
    owner: "Isaque Pimentel",
    ownerPresence: "online",
    status: "Executando",
    detail: "refresh de producao em andamento",
    forecast: "07:18",
    variance: "-1m",
    varianceTone: "positive",
    color: "blue",
  },
];

export const routineLinks: RoutineLink[] = [
  { from: "nasa", to: "ft-auto-emissao" },
  { from: "dwat", to: "ft-auto-recompensa" },
  { from: "ft-auto-emissao", to: "ft-auto-propostas-diarias" },
  { from: "ft-auto-emissao", to: "ft-auto-propostas-mensais" },
  {
    from: "ft-auto-propostas-diarias",
    to: "ft-auto-propostas-pendentes",
  },
  {
    from: "ft-auto-propostas-mensais",
    to: "ft-auto-propostas-pendentes",
  },
  { from: "ft-auto-emissao", to: "ft-auto-a-renovar" },
  { from: "ft-auto-emissao", to: "ft-auto-renovados" },
  { from: "ft-auto-propostas-pendentes", to: "ft-auto-renovados" },
  { from: "gsin", to: "ft-auto-sinistros-avisados" },
  { from: "gsin", to: "ft-auto-sinistros-pagos" },
  { from: "ft-auto-emissao", to: "ft-auto-cotacao" },
  { from: "crivo", to: "ft-auto-cotacao" },
  { from: "cotacao-variaveis", to: "ft-auto-cotacao" },
  { from: "ft-auto-emissao", to: "ft-auto-cotacao-d30" },
  { from: "crivo", to: "ft-auto-cotacao-d30" },
  { from: "cotacao-variaveis", to: "ft-auto-cotacao-d30" },
  { from: "ft-auto-emissao", to: "ft-auto-cbo" },
  { from: "cbo", to: "ft-auto-cbo" },
  { from: "dwat", to: "ft-prod-agreg-autore-diario" },
  { from: "dwre", to: "ft-prod-agreg-autore-diario" },
  { from: "edw", to: "ft-prod-agreg-autore-diario" },
  { from: "ft-auto-emissao", to: "cubo-emissao-auto" },
  { from: "ft-auto-recompensa", to: "cubo-recompensa" },
  {
    from: "ft-auto-propostas-diarias",
    to: "cubo-propostas-pendentes",
  },
  {
    from: "ft-auto-propostas-mensais",
    to: "cubo-propostas-pendentes",
  },
  { from: "ft-auto-cotacao", to: "cubo-cotacao-auto-individual" },
  { from: "ft-auto-cotacao-d30", to: "cubo-cotacao-auto-individual" },
  {
    from: "ft-auto-sinistros-avisados",
    to: "cubo-sinistros-avisados",
  },
  { from: "ft-auto-sinistros-pagos", to: "cubo-sinistros-pagos" },
  {
    from: "ft-prod-agreg-autore-diario",
    to: "cubo-producao-auto-re",
  },
];
